apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ include "httpbin.serviceAccountName" . }}
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: bitnami/kubectl:1.26.8
        command:
        - /bin/bash
        - -c
        - |
           #!/bin/bash
           ## Usage: ./install.sh [kubeconfig]

           if [ $# -ge 1 ] ; then
             export KUBECONFIG=$1
           fi

           NS=httpbin
           kubectl create ns $NS

           function installing_httpbin() {
             kubectl label ns $NS istio-injection=enabled --overwrite

             kubectl -n $NS apply -f ./utils/httpbin/svc.yaml
             kubectl -n $NS apply -f ./utils/httpbin/deployment.yaml
             kubectl -n $NS apply -f ./utils/httpbin/deployment-busybox-curl.yaml
             kubectl -n $NS apply -f ./utils/httpbin/vs.yaml
             return 0
           }

           # set commands for error handling.
           set -e
           set -o errexit   ## set -e : exit the script if any statement returns a non-true return value
           set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
           set -o errtrace  # trace ERR through 'time command' and other functions
           set -o pipefail  # trace ERR through pipes
           installing_httpbin  # calling function
