apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ include "s3.serviceAccountName" . }}
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: bitnami/kubectl:1.26.8
        command:
        - /bin/bash
        - -c
        - |
           #!/bin/bash
           function installing_Cred() {
           echo Istio label
           kubectl label ns $NS istio-injection=enabled --overwrite

           echo Creating secrets as per Minio native installation
           USER=$(kubectl -n minio get secret minio -o jsonpath='{.data.root-user}' | base64 --decode)
           PASS=$(kubectl -n minio get secret minio -o jsonpath='{.data.root-password}' | base64 --decode)

           export USER
           export PASS
           echo object-store secret and config map is set now.
           return 0
           } 

           # set commands for error handling.
           set -e
           set -o errexit   ## set -e : exit the script if any statement returns a non-true return value
           set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
           set -o errtrace  # trace ERR through 'time command' and other functions
           set -o pipefail  # trace ERR through pipes
           installing_Cred   # calling function
