## The data here is of generic interest to modules in different namespaces hence this is marked as global.
## Replace your domain names here.
## mosip-api-host:  External public access. (Typically required only in production rollouts).
## mosip-api-internal-host: Internal secure access over Wireguard.
## By default all domains and subdomains listed below point to mosip-api-internal-host. Modify this default behavior ONLY in production rollout as follows:
##     mosip-prereg-host:  Points to mosip-api-host.
##     mosip-pmp-host: Points to mosip-api-host.

apiVersion: v1
kind: ConfigMap
metadata:
  name: global
  namespace: default
data:
  installation-name: dev
  installation-domain: dev.mosip.net
  mosip-version: develop
  mosip-api-host: api.dev.mosip.net
  mosip-api-internal-host: api-internal.dev.mosip.net
  mosip-prereg-host: prereg.dev.mosip.net
  mosip-activemq-host: activemq.dev.mosip.net
  mosip-kibana-host: kibana.dev.mosip.net
  mosip-admin-host: admin.dev.mosip.net
  mosip-regclient-host: regclient.dev.mosip.net
  mosip-minio-host: minio.dev.mosip.net
  mosip-kafka-host: kafka.dev.mosip.net
  mosip-iam-external-host: iam.dev.mosip.net
  mosip-postgres-host: postgres.dev.mosip.net
  mosip-pmp-host: pmp.dev.mosip.net
  mosip-resident-host: resident.dev.mosip.net
  mosip-compliance-host: compliance.dev.mosip.net
  mosip-esignet-host: esignet.dev.mosip.net
  mosip-smtp-host: smtp.dev.mosip.net
  mosip-signup-host: signup.dev.mosip.net
  is_glowroot_env: absent
